In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


***tf.constant()***
<br>Tensors created in this way are immutable

In [2]:
ta = tf.constant(49)
ta

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [3]:
ta.shape

TensorShape([])

In [4]:
ta.dtype

tf.int32

In [5]:
tb = tf.constant([[2.,5.],[9.,4.]])
tb

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 5.],
       [9., 4.]], dtype=float32)>

In [6]:
tb.shape

TensorShape([2, 2])

In [7]:
tb.dtype

tf.float32

**Subsetting tensor**

In [8]:
tb[:,1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 4.], dtype=float32)>

In [9]:
tb[0,:]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

**Mathematical Operations**

In [10]:
ta+4

<tf.Tensor: shape=(), dtype=int32, numpy=53>

In [11]:
ta

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [12]:
tb

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 5.],
       [9., 4.]], dtype=float32)>

In [13]:
tf.transpose(tb)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 9.],
       [5., 4.]], dtype=float32)>

Matrix Multiplication

In [14]:
tc = tf.constant([[3.,4.],[7.,9.],[0.,2.]])
tc

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [7., 9.],
       [0., 2.]], dtype=float32)>

In [15]:
tc @ tb

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[42., 31.],
       [95., 71.],
       [18.,  8.]], dtype=float32)>

Calculations

In [16]:
tc

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [7., 9.],
       [0., 2.]], dtype=float32)>

In [17]:
tf.reduce_sum(tc)

<tf.Tensor: shape=(), dtype=float32, numpy=25.0>

In [18]:
tf.reduce_mean(tc)

<tf.Tensor: shape=(), dtype=float32, numpy=4.1666665>

In [19]:
tf.reduce_max(tc)

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

Some Maths

In [20]:
tf.math.log(tc)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.0986123, 1.3862944],
       [1.9459102, 2.1972246],
       [     -inf, 0.6931472]], dtype=float32)>

In [21]:
tf.math.exp(tc)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2.0085537e+01, 5.4598148e+01],
       [1.0966332e+03, 8.1030835e+03],
       [1.0000000e+00, 7.3890562e+00]], dtype=float32)>

**Type Conversions**

In [22]:
ta

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [23]:
td = tf.constant(57.)
td

<tf.Tensor: shape=(), dtype=float32, numpy=57.0>

In [24]:
ta + td

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [25]:
td +  tf.cast(ta, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=106.0>

***tf.Variable()***
<BR>Variables created in this way, are mutable and can be used to implement weights in neural networks

In [26]:
va = tf.Variable([[22.,35.,59.],[45.,98.,23.]])
va

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[22., 35., 59.],
       [45., 98., 23.]], dtype=float32)>

*tf.Variable* can perform same operations as *tf.Tensor* <BR>It has also some functions like *assign()*, *assign_add()* etc. 

In [39]:
va.assign(3*va)
va

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[198., 315., 531.],
       [405., 882., 207.]], dtype=float32)>

In [38]:
va*3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[198., 315., 531.],
       [405., 882., 207.]], dtype=float32)>

In [41]:
va

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[198., 315., 531.],
       [405., 882., 207.]], dtype=float32)>